// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutCard: typeof import('./src/components/About/AboutCard.vue')['default']
    AboutCardGlow: typeof import('./src/components/About/AboutCardGlow.vue')['default']
    AboutPill: typeof import('./src/components/About/AboutPill.vue')['default']
    BackButton: typeof import('./src/components/BackButton.vue')['default']
    ColumnHalf: typeof import('./src/components/Project/ColumnHalf.vue')['default']
    ColumnLeft: typeof import('./src/components/Project/ColumnLeft.vue')['default']
    FunCard: typeof import('./src/components/Fun/FunCard.vue')['default']
    FunCardOld: typeof import('./src/components/Fun/FunCardOld.vue')['default']
    FunCardTest: typeof import('./src/components/Fun/FunCardTest.vue')['default']
    HomeButton: typeof import('./src/components/HomeButton.vue')['default']
    'IIc:roundKeyboardArrowDown': typeof import('~icons/ic/round-keyboard-arrow-down')['default']
    IntroText: typeof import('./src/components/IntroText.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NavbarOld: typeof import('./src/components/NavbarOld.vue')['default']
    NotFoundText: typeof import('./src/components/NotFoundText.vue')['default']
    ProjectButton: typeof import('./src/components/Overview/ProjectButton.vue')['default']
    ProjectCardCenter: typeof import('./src/components/Overview/ProjectCardCenter.vue')['default']
    ProjectCardGlowLeft: typeof import('./src/components/Overview/ProjectCardGlowLeft.vue')['default']
    ProjectCardGlowRight: typeof import('./src/components/Overview/ProjectCardGlowRight.vue')['default']
    ProjectCardLeft: typeof import('./src/components/Overview/ProjectCardLeft.vue')['default']
    ProjectCardRight: typeof import('./src/components/Overview/ProjectCardRight.vue')['default']
    ProjectGallery: typeof import('./src/components/Project/ProjectGallery.vue')['default']
    ProjectGalleryOld: typeof import('./src/components/Project/ProjectGalleryOld.vue')['default']
    ProjectImage: typeof import('./src/components/Project/ProjectImage.vue')['default']
    ProjectImageFull: typeof import('./src/components/Project/ProjectImageFull.vue')['default']
    ProjectImageGallery: typeof import('./src/components/Project/ProjectImageGallery.vue')['default']
    ProjectImageHalf: typeof import('./src/components/Project/ProjectImageHalf.vue')['default']
    ProjectTags: typeof import('./src/components/Project/ProjectTags.vue')['default']
    ProjectTitle: typeof import('./src/components/Project/ProjectTitle.vue')['default']
    ProjectVideo: typeof import('./src/components/Project/ProjectVideo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
  }
}

export {}
