[build]
 command="npm run build"
 publish = "dist"

[context.v1]
  command = "true"
  publish = "."

[context.v2]
command="npm run build"
publish = "dist"

[context.v3]
command="npm run build"
publish = "dist"

[context.v4]
command="npm run build"
publish = "dist"

[context.master]
command="npm run build"
publish = "dist"